services:
  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rps
    depends_on:
      db:
        condition: service_healthy
  client:
    build:
      context: ./client
    ports:
      - 8080:80
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rps
      - POSTGRES_PASSWORD=pwd
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  