from os import environ


_DEBUG_PRIVATE_KEY = b"""-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQCsPaadWJJQRAVckmKmM4S34JH3Ch5j4uAyTsOeuVTWWdY7ZJ7c
b287YwJd1mLzNFEokopV46LRgHKKSdwP1ItywtOBBQCoSDB7TEAuQeei+ESQ3Igf
PLbhhYOhgW79ggTkdhxaXQhU5faL/IuiOFJKxhlGfvD8Kn3Z6NFPsbEVlQIDAQAB
AoGBAI6dyaz1XskZWXsqNoa5l8YNK69q8HjyrYLaVv3BJW8LGek5ypRprKd2tsnu
LyaDhkPa+rJddz6TZcP9njp5WjB+kn5NnPSoG7gJGqSmSq5RJidD3zYmntwpPyPH
w/cz8i3d5FCqZuWtW0/c+ksfaV4D/w/UDXi7Sg6oYvka0dRNAkEA93SnE1iIyZmF
67L7fJR4LZe1tci7i6WyPd+aEKIywNFTKMsCmy6H6PxAN5CuDzRxwO3a7T+EViRk
Xt518gfTywJBALIwJdXYZszxPjjoDQLy/dMOYElNPOBKRyocpyoc4MII3pvcK121
NfLalB32dRkzrIu3A7X5jJVSzYiyDCXNUB8CQQCb2Mkc4waLSXhRoJDIvk0OEd0s
VvbfFYUzeK70SOMEExF3wJusllqcfroHBMTK6LG321WlU/qJsjPQl/TacNmPAkAR
PkOLDCP2lSnWS+5maKlTcUK0FTtc4RM96gPrOVwuqrkQECBKMy0DUU+gDqeKRsvd
wVokk/+cu6SUI9a1Gcc1AkAcoz8DB498xHexAzmKGrpn7iNW8mZ0KXwnZrON9udE
I2cbspiANLVvrHTKZRRfcxXps4bEHeWVCWCChUwPniQS
-----END RSA PRIVATE KEY-----"""

_DEBUG_PUBLIC_KEY = b"""-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsPaadWJJQRAVckmKmM4S34JH3
Ch5j4uAyTsOeuVTWWdY7ZJ7cb287YwJd1mLzNFEokopV46LRgHKKSdwP1ItywtOB
BQCoSDB7TEAuQeei+ESQ3IgfPLbhhYOhgW79ggTkdhxaXQhU5faL/IuiOFJKxhlG
fvD8Kn3Z6NFPsbEVlQIDAQAB
-----END PUBLIC KEY-----"""

JWT_PRIVATE = environ.get('JWT_PRIVATE', _DEBUG_PRIVATE_KEY)
JWT_PUBLIC = environ.get('JWT_PUBLIC', _DEBUG_PUBLIC_KEY)

DB_USER = environ.get('DB_USER', 'postgres')
DB_PWD = environ.get('DB_PWD', 'pwd')
DB_HOST = environ.get('DB_HOST', '127.0.0.1')
DB_PORT = environ.get('DB_PORT', 5432)
DB_NAME = environ.get('DB_NAME', 'rps')

SALT = environ.get('SALT', 'OOcxepNl5RxDtYTZ2ky09FLc')
